baseURL = "https://alopezrivera.github.io/rl_and_scp_for_verifiable_mrto/"
languageCode = "en-us"
title = "Design And Optimization Of Multi-Rendezvous Manoeuvres Based On Reinforcement Learning And Convex Optimization"

[params]
  favicon = "favicon.ico"
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      unsafe = true
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      tables = true
      strikethrough = true
      taskList = true
      footnotes = true
      definitionList = true
      autolink = true
      linkify = true
      superscript = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'algol_nu'
    tabWidth = 4

[privacy.googleAnalytics]
  respectDoNotTrack = true